### ISSUE TITLE
Unittest fail for GamaClosure

### ISSUE THREAD

**Issue by qgeissmann** [theosysbio/means#3]
My understanding is that `GammaClosure` was changed, but the unittests were not updated.

```
======================================================================
ERROR: test_close_type_one (means.tests.test_closure_gamma.TestLogNormalCloser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quentin/comput/mean-git/src/means/tests/test_closure_gamma.py", line 98, in test_close_type_one
    closer = GammaClosure(max_order, type=1)
TypeError: __init__() got an unexpected keyword argument 'type'

======================================================================
ERROR: test_close_type_zero (means.tests.test_closure_gamma.TestLogNormalCloser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quentin/comput/mean-git/src/means/tests/test_closure_gamma.py", line 136, in test_close_type_zero
    closer = GammaClosure(max_order, type=0)
TypeError: __init__() got an unexpected keyword argument 'type'

----------------------------------------------------------------------
Ran 139 tests in 194.441s

FAILED (errors=2)
```

**Comment by elakatos** [comment]
Corrected.
